table MyMeasures
	lineageTag: ab776af6-2000-41e2-9309-1505e276dcf0

	measure 'Net Sales' = SUM(FactSale[NetSales])
		formatString: 0
		lineageTag: d5dca21b-348a-49ed-9a9a-1bbb7ffa471a

	measure 'Gross Sales' = SUM(FactSale[GrossSales])
		lineageTag: 5ef11ef7-e102-4fb2-94b6-8c2e632dca41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Quantity = SUM('FactSale'[Quantity])
		formatString: 0
		lineageTag: 3e0168ea-31be-4284-a73c-01fd6f25840b

	measure 'Avg Price' = DIVIDE([Net Sales], [Quantity])
		lineageTag: 63439183-018f-4123-bee8-ef5a7f2878f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales LY' = CALCULATE([Net Sales], SAMEPERIODLASTYEAR(DimDate[Date]))
		formatString: 0
		lineageTag: 56d92083-da71-4ef0-9e9a-2df915617773

	measure 'YoY %' =
			
			IF(
			    ISBLANK([Net Sales LY]),
			    BLANK(),
			    DIVIDE(
			        [Net Sales] - [Net Sales LY],
			        [Net Sales LY]
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: da498630-e2a6-40f8-8256-60e39e3ec6b0

	measure 'Avg Net Sales Per Day' = DIVIDE([Net Sales], [Quantity])
		lineageTag: e39da2eb-aca5-4547-8c4f-a799982c8fad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Sanity Flag' = ```
			
			IF(
			    ABS([YoY %]) > 1,
			    "CHECK",
			    "OK"
			)
			
			```
		lineageTag: bac0405a-21d4-4702-9af1-7f9c1ae9b808

	measure 'Has LY' = ```
			
			IF(
			    ISBLANK([Net Sales LY]),
			    "NO LY",
			    "OK"
			)
			
			```
		lineageTag: cd8289d0-3f6b-4f25-a4d2-a53776709009

	measure 'Net Sales Total Check' = ```
			
			IF(
			    [Net Sales] = CALCULATE([Net Sales], ALL(DimDate)),
			    "TOTAL",
			    "DETAIL"
			)
			
			```
		lineageTag: fd75d723-e7e4-45b6-b8ef-12a3bdbbbfd6

	measure 'YoY Δ' = [Net Sales] - [Net Sales LY]
		lineageTag: d2c19954-cd0f-4ab6-8dd3-c7cd6c2fd3e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MyMeasures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

